//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Menu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("University_Menu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /debug.
        /// </summary>
        internal static string ArgumentDebug {
            get {
                return ResourceManager.GetString("ArgumentDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /settings.
        /// </summary>
        internal static string ArgumentSettings {
            get {
                return ResourceManager.GetString("ArgumentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatUrl.
        /// </summary>
        internal static string ChatUrl {
            get {
                return ResourceManager.GetString("ChatUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultCheckup.
        /// </summary>
        internal static string DefaultCheckup {
            get {
                return ResourceManager.GetString("DefaultCheckup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultDemo.
        /// </summary>
        internal static string DefaultDemo {
            get {
                return ResourceManager.GetString("DefaultDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultHostName.
        /// </summary>
        internal static string DefaultHost {
            get {
                return ResourceManager.GetString("DefaultHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultLanguage.
        /// </summary>
        internal static string DefaultLang {
            get {
                return ResourceManager.GetString("DefaultLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaulLanguageEN.
        /// </summary>
        internal static string DefaultLangEN {
            get {
                return ResourceManager.GetString("DefaultLangEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaulLanguageFI.
        /// </summary>
        internal static string DefaultLangFI {
            get {
                return ResourceManager.GetString("DefaultLangFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultLangSeparator.
        /// </summary>
        internal static string DefaultLangSeparator {
            get {
                return ResourceManager.GetString("DefaultLangSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaulLanguageSV.
        /// </summary>
        internal static string DefaultLangSV {
            get {
                return ResourceManager.GetString("DefaultLangSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultNetwork.
        /// </summary>
        internal static string DefaultNetwork {
            get {
                return ResourceManager.GetString("DefaultNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultReboot.
        /// </summary>
        internal static string DefaultReboot {
            get {
                return ResourceManager.GetString("DefaultReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultRoaming.
        /// </summary>
        internal static string DefaultRoaming {
            get {
                return ResourceManager.GetString("DefaultRoaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultWarranty.
        /// </summary>
        internal static string DefaultWarranty {
            get {
                return ResourceManager.GetString("DefaultWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogError.
        /// </summary>
        internal static string DialogError {
            get {
                return ResourceManager.GetString("DialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogFileError.
        /// </summary>
        internal static string DialogFileError {
            get {
                return ResourceManager.GetString("DialogFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DialogSorry.
        /// </summary>
        internal static string DialogSorry {
            get {
                return ResourceManager.GetString("DialogSorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/efecte-cat1].
        /// </summary>
        internal static string EfecteCat1End {
            get {
                return ResourceManager.GetString("EfecteCat1End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [efecte-cat1].
        /// </summary>
        internal static string EfecteCat1Start {
            get {
                return ResourceManager.GetString("EfecteCat1Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/efecte-cat2].
        /// </summary>
        internal static string EfecteCat2End {
            get {
                return ResourceManager.GetString("EfecteCat2End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [efecte-cat2].
        /// </summary>
        internal static string EfecteCat2Start {
            get {
                return ResourceManager.GetString("EfecteCat2Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/efecte-cat3].
        /// </summary>
        internal static string EfecteCat3End {
            get {
                return ResourceManager.GetString("EfecteCat3End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [efecte-cat3].
        /// </summary>
        internal static string EfecteCat3Start {
            get {
                return ResourceManager.GetString("EfecteCat3Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/efecte-desc].
        /// </summary>
        internal static string EfecteDescEnd {
            get {
                return ResourceManager.GetString("EfecteDescEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [efecte-desc].
        /// </summary>
        internal static string EfecteDescStart {
            get {
                return ResourceManager.GetString("EfecteDescStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/efecte-email1].
        /// </summary>
        internal static string EfecteMail1End {
            get {
                return ResourceManager.GetString("EfecteMail1End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [efecte-email1].
        /// </summary>
        internal static string EfecteMail1Start {
            get {
                return ResourceManager.GetString("EfecteMail1Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/efecte-email2].
        /// </summary>
        internal static string EfecteMail2End {
            get {
                return ResourceManager.GetString("EfecteMail2End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [efecte-email2].
        /// </summary>
        internal static string EfecteMail2Start {
            get {
                return ResourceManager.GetString("EfecteMail2Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/efecte-reqt].
        /// </summary>
        internal static string EfecteReqtEnd {
            get {
                return ResourceManager.GetString("EfecteReqtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [efecte-reqt].
        /// </summary>
        internal static string EfecteReqtStart {
            get {
                return ResourceManager.GetString("EfecteReqtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/efecte-sg].
        /// </summary>
        internal static string EfecteSgEnd {
            get {
                return ResourceManager.GetString("EfecteSgEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [efecte-sg].
        /// </summary>
        internal static string EfecteSgStart {
            get {
                return ResourceManager.GetString("EfecteSgStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorText.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecuteTag.
        /// </summary>
        internal static string ExecuteTag {
            get {
                return ResourceManager.GetString("ExecuteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string HeaderTag {
            get {
                return ResourceManager.GetString("HeaderTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MenuEN {
            get {
                object obj = ResourceManager.GetObject("MenuEN", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MenuFI {
            get {
                object obj = ResourceManager.GetObject("MenuFI", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MenuSV {
            get {
                object obj = ResourceManager.GetObject("MenuSV", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ModuleChat {
            get {
                return ResourceManager.GetString("ModuleChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoAdditional.
        /// </summary>
        internal static string ModuleCompAdd {
            get {
                return ResourceManager.GetString("ModuleCompAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoAddress.
        /// </summary>
        internal static string ModuleCompAddress {
            get {
                return ResourceManager.GetString("ModuleCompAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoBuilding.
        /// </summary>
        internal static string ModuleCompBuilding {
            get {
                return ResourceManager.GetString("ModuleCompBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoCPU.
        /// </summary>
        internal static string ModuleCompCPU {
            get {
                return ResourceManager.GetString("ModuleCompCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoHostname.
        /// </summary>
        internal static string ModuleCompHostname {
            get {
                return ResourceManager.GetString("ModuleCompHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfo.
        /// </summary>
        internal static string ModuleCompInfo {
            get {
                return ResourceManager.GetString("ModuleCompInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoIsEncrypt.
        /// </summary>
        internal static string ModuleCompIsEncrypt {
            get {
                return ResourceManager.GetString("ModuleCompIsEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoMemory.
        /// </summary>
        internal static string ModuleCompMemory {
            get {
                return ResourceManager.GetString("ModuleCompMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoModel.
        /// </summary>
        internal static string ModuleCompModel {
            get {
                return ResourceManager.GetString("ModuleCompModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoNotEncrypt.
        /// </summary>
        internal static string ModuleCompNotEncrypt {
            get {
                return ResourceManager.GetString("ModuleCompNotEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoOS.
        /// </summary>
        internal static string ModuleCompOS {
            get {
                return ResourceManager.GetString("ModuleCompOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoProfit.
        /// </summary>
        internal static string ModuleCompProfit {
            get {
                return ResourceManager.GetString("ModuleCompProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoRoom.
        /// </summary>
        internal static string ModuleCompRoom {
            get {
                return ResourceManager.GetString("ModuleCompRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoSN.
        /// </summary>
        internal static string ModuleCompSN {
            get {
                return ResourceManager.GetString("ModuleCompSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoVersion.
        /// </summary>
        internal static string ModuleCompVersion {
            get {
                return ResourceManager.GetString("ModuleCompVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoWarranty.
        /// </summary>
        internal static string ModuleCompWarranty {
            get {
                return ResourceManager.GetString("ModuleCompWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoWarrantyTooltipLess.
        /// </summary>
        internal static string ModuleCompWarrantyTooltipLess {
            get {
                return ResourceManager.GetString("ModuleCompWarrantyTooltipLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoWarrantyTooltipMore.
        /// </summary>
        internal static string ModuleCompWarrantyTooltipMore {
            get {
                return ResourceManager.GetString("ModuleCompWarrantyTooltipMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoWarrantyUrl.
        /// </summary>
        internal static string ModuleCompWarrantyUrl {
            get {
                return ResourceManager.GetString("ModuleCompWarrantyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfoWinUpdates.
        /// </summary>
        internal static string ModuleCompWinUpd {
            get {
                return ResourceManager.GetString("ModuleCompWinUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleCopyClipboard.
        /// </summary>
        internal static string ModuleCopyClipboard {
            get {
                return ResourceManager.GetString("ModuleCopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWA.
        /// </summary>
        internal static string ModuleOWA {
            get {
                return ResourceManager.GetString("ModuleOWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportRequest.
        /// </summary>
        internal static string ModuleSupportRequest {
            get {
                return ResourceManager.GetString("ModuleSupportRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleTooltip.
        /// </summary>
        internal static string ModuleTooltip {
            get {
                return ResourceManager.GetString("ModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationAccountExpires.
        /// </summary>
        internal static string ModuleUserAccountExpires {
            get {
                return ResourceManager.GetString("ModuleUserAccountExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationPasswordUrl.
        /// </summary>
        internal static string ModuleUserAccountUrl {
            get {
                return ResourceManager.GetString("ModuleUserAccountUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationAdditional.
        /// </summary>
        internal static string ModuleUserAdd {
            get {
                return ResourceManager.GetString("ModuleUserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationDiskSpace.
        /// </summary>
        internal static string ModuleUserDiskSpace {
            get {
                return ResourceManager.GetString("ModuleUserDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleUserDiskSpaceFree.
        /// </summary>
        internal static string ModuleUserDiskSpaceFree {
            get {
                return ResourceManager.GetString("ModuleUserDiskSpaceFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationEmail.
        /// </summary>
        internal static string ModuleUserEmail {
            get {
                return ResourceManager.GetString("ModuleUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationFullName.
        /// </summary>
        internal static string ModuleUserFullName {
            get {
                return ResourceManager.GetString("ModuleUserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationHomeDirectory.
        /// </summary>
        internal static string ModuleUserHomeDir {
            get {
                return ResourceManager.GetString("ModuleUserHomeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationHomeDrive.
        /// </summary>
        internal static string ModuleUserHomeDrive {
            get {
                return ResourceManager.GetString("ModuleUserHomeDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationHomeTooltip.
        /// </summary>
        internal static string ModuleUserHomeTooltip {
            get {
                return ResourceManager.GetString("ModuleUserHomeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformation.
        /// </summary>
        internal static string ModuleUserInfo {
            get {
                return ResourceManager.GetString("ModuleUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationInstructionsTooltip.
        /// </summary>
        internal static string ModuleUserInstructionsTooltip {
            get {
                return ResourceManager.GetString("ModuleUserInstructionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationMailbox.
        /// </summary>
        internal static string ModuleUserMailbox {
            get {
                return ResourceManager.GetString("ModuleUserMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationMailboxCloud.
        /// </summary>
        internal static string ModuleUserMailboxCloud {
            get {
                return ResourceManager.GetString("ModuleUserMailboxCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationMailboxLocal.
        /// </summary>
        internal static string ModuleUserMailboxLocal {
            get {
                return ResourceManager.GetString("ModuleUserMailboxLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationUsername.
        /// </summary>
        internal static string ModuleUserName {
            get {
                return ResourceManager.GetString("ModuleUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationPasswordUrl.
        /// </summary>
        internal static string ModuleUserPasswordUrl {
            get {
                return ResourceManager.GetString("ModuleUserPasswordUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationPrinter.
        /// </summary>
        internal static string ModuleUserPrinter {
            get {
                return ResourceManager.GetString("ModuleUserPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationPWChanged.
        /// </summary>
        internal static string ModuleUserPWChanged {
            get {
                return ResourceManager.GetString("ModuleUserPWChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformationPWExpires.
        /// </summary>
        internal static string ModuleUserPWExpires {
            get {
                return ResourceManager.GetString("ModuleUserPWExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameErrorText.
        /// </summary>
        internal static string NameErrorText {
            get {
                return ResourceManager.GetString("NameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /menu.
        /// </summary>
        internal static string NodeAddMenu {
            get {
                return ResourceManager.GetString("NodeAddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /local/menu.
        /// </summary>
        internal static string NodeLocalMenu {
            get {
                return ResourceManager.GetString("NodeLocalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /local/settings.
        /// </summary>
        internal static string NodeLocalSettings {
            get {
                return ResourceManager.GetString("NodeLocalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /user/settings.
        /// </summary>
        internal static string NodeUserSettings {
            get {
                return ResourceManager.GetString("NodeUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotifyBalloonTitle.
        /// </summary>
        internal static string NotifyBalloonTitle {
            get {
                return ResourceManager.GetString("NotifyBalloonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckupBalloonText.
        /// </summary>
        internal static string NotifyCheckupBalloonText {
            get {
                return ResourceManager.GetString("NotifyCheckupBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NotifyIcon {
            get {
                object obj = ResourceManager.GetObject("NotifyIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NotifyIcon_Black {
            get {
                object obj = ResourceManager.GetObject("NotifyIcon_Black", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NotifyIcon_Blue {
            get {
                object obj = ResourceManager.GetObject("NotifyIcon_Blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NotifyIcon_Orange {
            get {
                object obj = ResourceManager.GetObject("NotifyIcon_Orange", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NotifyIcon_Red {
            get {
                object obj = ResourceManager.GetObject("NotifyIcon_Red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkBalloonText.
        /// </summary>
        internal static string NotifyNetworkBalloonText {
            get {
                return ResourceManager.GetString("NotifyNetworkBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotifyRebootBalloonText.
        /// </summary>
        internal static string NotifyRebootBalloonText {
            get {
                return ResourceManager.GetString("NotifyRebootBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WelcomeText.
        /// </summary>
        internal static string NotifyWelcomeText {
            get {
                return ResourceManager.GetString("NotifyWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WelcomeTitle.
        /// </summary>
        internal static string NotifyWelcomeTitle {
            get {
                return ResourceManager.GetString("NotifyWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParametersTag.
        /// </summary>
        internal static string ParametersTag {
            get {
                return ResourceManager.GetString("ParametersTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ProgramIcon {
            get {
                object obj = ResourceManager.GetObject("ProgramIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        internal static string SeparatorTag {
            get {
                return ResourceManager.GetString("SeparatorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip.
        /// </summary>
        internal static string TooltipTag {
            get {
                return ResourceManager.GetString("TooltipTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIAttachmentAdd.
        /// </summary>
        internal static string UIAttachmentAdd {
            get {
                return ResourceManager.GetString("UIAttachmentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIAttachmentClear.
        /// </summary>
        internal static string UIAttachmentClear {
            get {
                return ResourceManager.GetString("UIAttachmentClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIAttachmentCount0.
        /// </summary>
        internal static string UIAttachmentCount0 {
            get {
                return ResourceManager.GetString("UIAttachmentCount0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIAttachmentCount1.
        /// </summary>
        internal static string UIAttachmentCount1 {
            get {
                return ResourceManager.GetString("UIAttachmentCount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIAttachmentCount2.
        /// </summary>
        internal static string UIAttachmentCount2 {
            get {
                return ResourceManager.GetString("UIAttachmentCount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UICheckupURL.
        /// </summary>
        internal static string UICheckupURL {
            get {
                return ResourceManager.GetString("UICheckupURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UICheckupWTDConnect.
        /// </summary>
        internal static string UICheckupWTDConnect {
            get {
                return ResourceManager.GetString("UICheckupWTDConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UICheckupWTDTitle.
        /// </summary>
        internal static string UICheckupWTDTitle {
            get {
                return ResourceManager.GetString("UICheckupWTDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UICheckupWTDVPN.
        /// </summary>
        internal static string UICheckupWTDVPN {
            get {
                return ResourceManager.GetString("UICheckupWTDVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UICheckupWTDWeb.
        /// </summary>
        internal static string UICheckupWTDWeb {
            get {
                return ResourceManager.GetString("UICheckupWTDWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIHelp.
        /// </summary>
        internal static string UIHelp {
            get {
                return ResourceManager.GetString("UIHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIHelpdeskSupport.
        /// </summary>
        internal static string UIHelpdeskSupport {
            get {
                return ResourceManager.GetString("UIHelpdeskSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIHelpdeskTitle.
        /// </summary>
        internal static string UIHelpdeskTitle {
            get {
                return ResourceManager.GetString("UIHelpdeskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIHelpUrl.
        /// </summary>
        internal static string UIHelpUrl {
            get {
                return ResourceManager.GetString("UIHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIMessageInfo.
        /// </summary>
        internal static string UIMessageInfo {
            get {
                return ResourceManager.GetString("UIMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UINetworkDiskSpaceCalc.
        /// </summary>
        internal static string UINetworkDiskSpaceCalc {
            get {
                return ResourceManager.GetString("UINetworkDiskSpaceCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UINetworkDiskSpaceInfo.
        /// </summary>
        internal static string UINetworkDiskSpaceInfo {
            get {
                return ResourceManager.GetString("UINetworkDiskSpaceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UINetworkDiskSpaceInfoNA.
        /// </summary>
        internal static string UINetworkDiskSpaceInfoNA {
            get {
                return ResourceManager.GetString("UINetworkDiskSpaceInfoNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UINetworkURL.
        /// </summary>
        internal static string UINetworkURL {
            get {
                return ResourceManager.GetString("UINetworkURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UINetworkWTDHome.
        /// </summary>
        internal static string UINetworkWTDHome {
            get {
                return ResourceManager.GetString("UINetworkWTDHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UINetworkWTDHYData.
        /// </summary>
        internal static string UINetworkWTDHYData {
            get {
                return ResourceManager.GetString("UINetworkWTDHYData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UINoNotify.
        /// </summary>
        internal static string UINoNotify {
            get {
                return ResourceManager.GetString("UINoNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UINoNotifyText.
        /// </summary>
        internal static string UINoNotifyText {
            get {
                return ResourceManager.GetString("UINoNotifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UINotifyTitle.
        /// </summary>
        internal static string UINotifyTitle {
            get {
                return ResourceManager.GetString("UINotifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIPreviewAttachmentError.
        /// </summary>
        internal static string UIPreviewAttachmentError {
            get {
                return ResourceManager.GetString("UIPreviewAttachmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIPreviewCancel.
        /// </summary>
        internal static string UIPreviewCancel {
            get {
                return ResourceManager.GetString("UIPreviewCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIPreviewCanNotSend.
        /// </summary>
        internal static string UIPreviewCanNotSend {
            get {
                return ResourceManager.GetString("UIPreviewCanNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIPreviewMessage.
        /// </summary>
        internal static string UIPreviewMessage {
            get {
                return ResourceManager.GetString("UIPreviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIPreviewSendError.
        /// </summary>
        internal static string UIPreviewSendError {
            get {
                return ResourceManager.GetString("UIPreviewSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIPreviewSendSuccess.
        /// </summary>
        internal static string UIPreviewSendSuccess {
            get {
                return ResourceManager.GetString("UIPreviewSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIRestartButton.
        /// </summary>
        internal static string UIRestartButton {
            get {
                return ResourceManager.GetString("UIRestartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIRestartConfirm.
        /// </summary>
        internal static string UIRestartConfirm {
            get {
                return ResourceManager.GetString("UIRestartConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISettings.
        /// </summary>
        internal static string UISettings {
            get {
                return ResourceManager.GetString("UISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISettingsAbout.
        /// </summary>
        internal static string UISettingsAbout {
            get {
                return ResourceManager.GetString("UISettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISettingsAppearance.
        /// </summary>
        internal static string UISettingsAppearance {
            get {
                return ResourceManager.GetString("UISettingsAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISettingsApply.
        /// </summary>
        internal static string UISettingsApply {
            get {
                return ResourceManager.GetString("UISettingsApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISettingsDark.
        /// </summary>
        internal static string UISettingsDark {
            get {
                return ResourceManager.GetString("UISettingsDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISettingsFontSize.
        /// </summary>
        internal static string UISettingsFontSize {
            get {
                return ResourceManager.GetString("UISettingsFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISettingsLanguage.
        /// </summary>
        internal static string UISettingsLanguage {
            get {
                return ResourceManager.GetString("UISettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISettingsLarge.
        /// </summary>
        internal static string UISettingsLarge {
            get {
                return ResourceManager.GetString("UISettingsLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISettingsLight.
        /// </summary>
        internal static string UISettingsLight {
            get {
                return ResourceManager.GetString("UISettingsLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISettingsSmall.
        /// </summary>
        internal static string UISettingsSmall {
            get {
                return ResourceManager.GetString("UISettingsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISettingsTheme.
        /// </summary>
        internal static string UISettingsTheme {
            get {
                return ResourceManager.GetString("UISettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportAgain.
        /// </summary>
        internal static string UISupportAgain {
            get {
                return ResourceManager.GetString("UISupportAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportAttachment.
        /// </summary>
        internal static string UISupportAttachment {
            get {
                return ResourceManager.GetString("UISupportAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportAttachments.
        /// </summary>
        internal static string UISupportAttachments {
            get {
                return ResourceManager.GetString("UISupportAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------&lt;-.
        /// </summary>
        internal static string UISupportAutoEnd {
            get {
                return ResourceManager.GetString("UISupportAutoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&gt;----------------------------.
        /// </summary>
        internal static string UISupportAutoStart {
            get {
                return ResourceManager.GetString("UISupportAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportBasicMessage.
        /// </summary>
        internal static string UISupportBasicMessage {
            get {
                return ResourceManager.GetString("UISupportBasicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportBulletin.
        /// </summary>
        internal static string UISupportBulletin {
            get {
                return ResourceManager.GetString("UISupportBulletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportButtonClear.
        /// </summary>
        internal static string UISupportButtonClear {
            get {
                return ResourceManager.GetString("UISupportButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportButtonEdit.
        /// </summary>
        internal static string UISupportButtonEdit {
            get {
                return ResourceManager.GetString("UISupportButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportButtonPreview.
        /// </summary>
        internal static string UISupportButtonPreview {
            get {
                return ResourceManager.GetString("UISupportButtonPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportButtonSend.
        /// </summary>
        internal static string UISupportButtonSend {
            get {
                return ResourceManager.GetString("UISupportButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportCategory.
        /// </summary>
        internal static string UISupportCategory {
            get {
                return ResourceManager.GetString("UISupportCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UICategoryPurchases.
        /// </summary>
        internal static string UISupportCategoryPurchases {
            get {
                return ResourceManager.GetString("UISupportCategoryPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UICategorySoftwareInstallation.
        /// </summary>
        internal static string UISupportCategorySI {
            get {
                return ResourceManager.GetString("UISupportCategorySI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportForm.
        /// </summary>
        internal static string UISupportForm {
            get {
                return ResourceManager.GetString("UISupportForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportInfo.
        /// </summary>
        internal static string UISupportInfo {
            get {
                return ResourceManager.GetString("UISupportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportMessage.
        /// </summary>
        internal static string UISupportMessage {
            get {
                return ResourceManager.GetString("UISupportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportMessageTitle.
        /// </summary>
        internal static string UISupportMessageTitle {
            get {
                return ResourceManager.GetString("UISupportMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportMessageUrl.
        /// </summary>
        internal static string UISupportMessageUrl {
            get {
                return ResourceManager.GetString("UISupportMessageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportNotIdentified.
        /// </summary>
        internal static string UISupportNotIdentified {
            get {
                return ResourceManager.GetString("UISupportNotIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportOther.
        /// </summary>
        internal static string UISupportOther {
            get {
                return ResourceManager.GetString("UISupportOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPreview.
        /// </summary>
        internal static string UISupportPreview {
            get {
                return ResourceManager.GetString("UISupportPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuAcceptor.
        /// </summary>
        internal static string UISupportPuAcceptor {
            get {
                return ResourceManager.GetString("UISupportPuAcceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuAcceptorStyle.
        /// </summary>
        internal static string UISupportPuAcceptorStyle {
            get {
                return ResourceManager.GetString("UISupportPuAcceptorStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuBulletinInfo.
        /// </summary>
        internal static string UISupportPuBulletinInfo {
            get {
                return ResourceManager.GetString("UISupportPuBulletinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuDevice.
        /// </summary>
        internal static string UISupportPuDevice {
            get {
                return ResourceManager.GetString("UISupportPuDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuDevice1.
        /// </summary>
        internal static string UISupportPuDevice1 {
            get {
                return ResourceManager.GetString("UISupportPuDevice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuDevice2.
        /// </summary>
        internal static string UISupportPuDevice2 {
            get {
                return ResourceManager.GetString("UISupportPuDevice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuDevice3.
        /// </summary>
        internal static string UISupportPuDevice3 {
            get {
                return ResourceManager.GetString("UISupportPuDevice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuEndUser.
        /// </summary>
        internal static string UISupportPuEndUser {
            get {
                return ResourceManager.GetString("UISupportPuEndUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuEndUserStyle.
        /// </summary>
        internal static string UISupportPuEndUserStyle {
            get {
                return ResourceManager.GetString("UISupportPuEndUserStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuFlammaURL.
        /// </summary>
        internal static string UISupportPuFlammaURL {
            get {
                return ResourceManager.GetString("UISupportPuFlammaURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuMe.
        /// </summary>
        internal static string UISupportPuMe {
            get {
                return ResourceManager.GetString("UISupportPuMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuOrders.
        /// </summary>
        internal static string UISupportPuOrders {
            get {
                return ResourceManager.GetString("UISupportPuOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuType.
        /// </summary>
        internal static string UISupportPuType {
            get {
                return ResourceManager.GetString("UISupportPuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuTypeNew.
        /// </summary>
        internal static string UISupportPuTypeNew {
            get {
                return ResourceManager.GetString("UISupportPuTypeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuTypeReplace.
        /// </summary>
        internal static string UISupportPuTypeReplace {
            get {
                return ResourceManager.GetString("UISupportPuTypeReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuTypeStyle.
        /// </summary>
        internal static string UISupportPuTypeStyle {
            get {
                return ResourceManager.GetString("UISupportPuTypeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuWBS.
        /// </summary>
        internal static string UISupportPuWBS {
            get {
                return ResourceManager.GetString("UISupportPuWBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportPuWBSStyle.
        /// </summary>
        internal static string UISupportPuWBSStyle {
            get {
                return ResourceManager.GetString("UISupportPuWBSStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSIBulletinInfo.
        /// </summary>
        internal static string UISupportSIBulletinInfo {
            get {
                return ResourceManager.GetString("UISupportSIBulletinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSIBulletinSoftwarePortal.
        /// </summary>
        internal static string UISupportSIBulletinSoftwarePortal {
            get {
                return ResourceManager.GetString("UISupportSIBulletinSoftwarePortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSIComments.
        /// </summary>
        internal static string UISupportSIComments {
            get {
                return ResourceManager.GetString("UISupportSIComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSIInstallation.
        /// </summary>
        internal static string UISupportSIInstallation {
            get {
                return ResourceManager.GetString("UISupportSIInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSIInstallationAnyTime.
        /// </summary>
        internal static string UISupportSIInstallationAnyTime {
            get {
                return ResourceManager.GetString("UISupportSIInstallationAnyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSIInstallationInfo.
        /// </summary>
        internal static string UISupportSIInstallationInfo {
            get {
                return ResourceManager.GetString("UISupportSIInstallationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSIInstallationOption.
        /// </summary>
        internal static string UISupportSIInstallationOption {
            get {
                return ResourceManager.GetString("UISupportSIInstallationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSIInstallationPickDate.
        /// </summary>
        internal static string UISupportSIInstallationPickDate {
            get {
                return ResourceManager.GetString("UISupportSIInstallationPickDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSIInstallationTime.
        /// </summary>
        internal static string UISupportSIInstallationTime {
            get {
                return ResourceManager.GetString("UISupportSIInstallationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSIInstructions.
        /// </summary>
        internal static string UISupportSIInstructions {
            get {
                return ResourceManager.GetString("UISupportSIInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSILicense.
        /// </summary>
        internal static string UISupportSILicense {
            get {
                return ResourceManager.GetString("UISupportSILicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSILicense1.
        /// </summary>
        internal static string UISupportSILicense1 {
            get {
                return ResourceManager.GetString("UISupportSILicense1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSILicense2.
        /// </summary>
        internal static string UISupportSILicense2 {
            get {
                return ResourceManager.GetString("UISupportSILicense2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSILicenseInfo.
        /// </summary>
        internal static string UISupportSILicenseInfo {
            get {
                return ResourceManager.GetString("UISupportSILicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSIPortalURL.
        /// </summary>
        internal static string UISupportSIPortalURL {
            get {
                return ResourceManager.GetString("UISupportSIPortalURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSISoftware.
        /// </summary>
        internal static string UISupportSISoftware {
            get {
                return ResourceManager.GetString("UISupportSISoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportSubject.
        /// </summary>
        internal static string UISupportSubject {
            get {
                return ResourceManager.GetString("UISupportSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportTitle.
        /// </summary>
        internal static string UISupportTitle {
            get {
                return ResourceManager.GetString("UISupportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UISupportWait.
        /// </summary>
        internal static string UISupportWait {
            get {
                return ResourceManager.GetString("UISupportWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIWarrantyWTDTitle.
        /// </summary>
        internal static string UIWarrantyWTDTitle {
            get {
                return ResourceManager.GetString("UIWarrantyWTDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMIconText.
        /// </summary>
        internal static string UMIconText {
            get {
                return ResourceManager.GetString("UMIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMIconTextNotify.
        /// </summary>
        internal static string UMIconTextNotify {
            get {
                return ResourceManager.GetString("UMIconTextNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIAccountExpire.
        /// </summary>
        internal static string UserAccountExpire {
            get {
                return ResourceManager.GetString("UserAccountExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckupBalloon.
        /// </summary>
        internal static string UserCheckupBalloon {
            get {
                return ResourceManager.GetString("UserCheckupBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckupExclude.
        /// </summary>
        internal static string UserCheckupExclude {
            get {
                return ResourceManager.GetString("UserCheckupExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastCheckupPopup.
        /// </summary>
        internal static string UserCheckupPopup {
            get {
                return ResourceManager.GetString("UserCheckupPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string UserColor {
            get {
                return ResourceManager.GetString("UserColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIEmail.
        /// </summary>
        internal static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIEmailService.
        /// </summary>
        internal static string UserEmailService {
            get {
                return ResourceManager.GetString("UserEmailService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string UserFont {
            get {
                return ResourceManager.GetString("UserFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIFullName.
        /// </summary>
        internal static string UserFullName {
            get {
                return ResourceManager.GetString("UserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIHomeDirectory.
        /// </summary>
        internal static string UserHomeDir {
            get {
                return ResourceManager.GetString("UserHomeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIHomeDrive.
        /// </summary>
        internal static string UserHomeDrive {
            get {
                return ResourceManager.GetString("UserHomeDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string UserLanguage {
            get {
                return ResourceManager.GetString("UserLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastCheckupBalloon.
        /// </summary>
        internal static string UserLastCheckupBalloon {
            get {
                return ResourceManager.GetString("UserLastCheckupBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastNetworkBalloon.
        /// </summary>
        internal static string UserLastNetworkBalloon {
            get {
                return ResourceManager.GetString("UserLastNetworkBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastRebootBalloon.
        /// </summary>
        internal static string UserLastRebootBalloon {
            get {
                return ResourceManager.GetString("UserLastRebootBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastShown.
        /// </summary>
        internal static string UserLastShown {
            get {
                return ResourceManager.GetString("UserLastShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkBalloon.
        /// </summary>
        internal static string UserNetworkBalloon {
            get {
                return ResourceManager.GetString("UserNetworkBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkExclude.
        /// </summary>
        internal static string UserNetworkExclude {
            get {
                return ResourceManager.GetString("UserNetworkExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastNetworkPopup.
        /// </summary>
        internal static string UserNetworkPopup {
            get {
                return ResourceManager.GetString("UserNetworkPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIPasswordExpire.
        /// </summary>
        internal static string UserPasswordExpire {
            get {
                return ResourceManager.GetString("UserPasswordExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIPasswordSet.
        /// </summary>
        internal static string UserPasswordSet {
            get {
                return ResourceManager.GetString("UserPasswordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RebootBalloon.
        /// </summary>
        internal static string UserRebootBalloon {
            get {
                return ResourceManager.GetString("UserRebootBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RebootExclude.
        /// </summary>
        internal static string UserRebootExclude {
            get {
                return ResourceManager.GetString("UserRebootExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastRebootPopup.
        /// </summary>
        internal static string UserRebootPopup {
            get {
                return ResourceManager.GetString("UserRebootPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoamingCount.
        /// </summary>
        internal static string UserRoaming {
            get {
                return ResourceManager.GetString("UserRoaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoamingExclude.
        /// </summary>
        internal static string UserRoamingExclude {
            get {
                return ResourceManager.GetString("UserRoamingExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string UserTheme {
            get {
                return ResourceManager.GetString("UserTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarrantyExclude.
        /// </summary>
        internal static string UserWarrantyExclude {
            get {
                return ResourceManager.GetString("UserWarrantyExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastWarrantyPopup.
        /// </summary>
        internal static string UserWarrantyPopup {
            get {
                return ResourceManager.GetString("UserWarrantyPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WelcomeCount.
        /// </summary>
        internal static string UserWelcome {
            get {
                return ResourceManager.GetString("UserWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 22.17,36.4216L 25.3369,36.4216L 25.3369,31.6711C 25.3369,24.6745 31.0087,19.0027 38.0053,19.0027C 45.0019,19.0027 50.6737,24.6745 50.6737,31.6711L 50.6737,36.4216L 53.841,36.4216L 53.8411,57.008L 22.17,57.008L 22.17,36.4216 Z M 45.9231,31.6711C 45.9231,27.2982 42.3782,23.7533 38.0053,23.7533C 33.6324,23.7533 30.0875,27.2982 30.0875,31.6711L 30.0875,36.4216L 45.923,36.4216L 45.9231,31.6711 Z.
        /// </summary>
        internal static string VecktorLock {
            get {
                return ResourceManager.GetString("VecktorLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 22.1698,36.4215L 25.3366,36.4215L 25.3367,31.6711C 25.3367,24.6745 31.0085,19.0027 38.0051,19.0027C 45.0017,19.0027 50.6735,24.6745 50.6735,31.6711L 45.9228,31.6711C 45.9228,27.2982 42.3779,23.7533 38.0051,23.7533C 33.6322,23.7533 30.0873,27.2982 30.0873,31.6711L 30.0873,36.4216L 53.8408,36.4215L 53.8409,57.008L 22.1698,57.008L 22.1698,36.4215 Z.
        /// </summary>
        internal static string VecktorLockOpen {
            get {
                return ResourceManager.GetString("VecktorLockOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 27,20L 38.75,20L 37.75,19L 24,19L 24,50L 27,50L 27,20 Z M 46.25,20L 59,32.75L 59,59L 27,59L 27,54L 20,54L 20,15L 39.25,15L 44.25,20L 46.25,20 Z M 31,24L 31,55L 55,55L 55,37L 42,37L 42,24L 31,24 Z M 46,25.25L 46,33L 53.75,33L 46,25.25 Z.
        /// </summary>
        internal static string VectorCopy {
            get {
                return ResourceManager.GetString("VectorCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 12.2495,36.8804L 36.8804,12.2496C 37.4987,11.6312 38.5012,11.6312 39.1196,12.2496L 63.7504,36.8804C 64.3688,37.4988 64.3688,38.5013 63.7504,39.1196L 39.1196,63.7505C 38.5013,64.3688 37.4987,64.3688 36.8804,63.7505L 12.2495,39.1196C 11.6312,38.5013 11.6312,37.4988 12.2495,36.8804 Z M 38,45.125C 36.0325,45.125 34.4375,46.72 34.4375,48.6875C 34.4375,50.655 36.0325,52.25 38,52.25C 39.9675,52.25 41.5625,50.655 41.5625,48.6875C 41.5625,46.72 39.9675,45.125 38,45.125 Z M 34.4375,23.75L 35.625,42.75L 40.375,42 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VectorHazard {
            get {
                return ResourceManager.GetString("VectorHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 38,19C 48.4934,19 57,27.5066 57,38C 57,48.4934 48.4934,57 38,57C 27.5066,57 19,48.4934 19,38C 19,27.5066 27.5066,19 38,19 Z M 33.25,33.25L 33.25,36.4167L 36.4166,36.4167L 36.4166,47.5L 33.25,47.5L 33.25,50.6667L 44.3333,50.6667L 44.3333,47.5L 41.1666,47.5L 41.1666,36.4167L 41.1666,33.25L 33.25,33.25 Z M 38.7917,25.3333C 37.48,25.3333 36.4167,26.3967 36.4167,27.7083C 36.4167,29.02 37.48,30.0833 38.7917,30.0833C 40.1033,30.0833 41.1667,29.02 41.1667,27.7083C 41.1667,26.3967 40.1033,25.3333 38.7917,25.333 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VectorInfo {
            get {
                return ResourceManager.GetString("VectorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 M 57, 28.0001L 57.0002, 44.9999L 55.0002, 44.9999L 55.0002, 30L 42.0002, 29.9999L 42.0002, 28L 57, 28.0001 Z M 54, 49.0002L 42.0001, 49L 42, 38.0001L 45.5032, 40.7501L 53.9998, 33.5004L 54, 49.0002 Z M 54, 31.0001L 53.9998, 31.7503L 45.4998, 38.7503L 42.0001, 36L 42.0002, 31L 54, 31.0001 Z M 18.9998, 23.5002L 40.9999, 20.0001L 40.9999, 56.0001L 18.9998, 52.5002L 18.9998, 23.5002 Z M 29.7823, 44.5427C 31.1047, 44.6242 32.6081, 44.0316 33.4484, 43.0072C 35.2038, 40.8676 35.3479, 37.1917 34.085, 34.729C 33. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VectorOWA {
            get {
                return ResourceManager.GetString("VectorOWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to umadd*.xml.
        /// </summary>
        internal static string XMLFileFilter {
            get {
                return ResourceManager.GetString("XMLFileFilter", resourceCulture);
            }
        }
    }
}
